### ISSUE TITLE
Upcoming Classes Section: Stock Market Course

### ISSUE THREAD

**Issue by haoteng10** [Elevate-the-Future-NY/ny.elevatethefuture.org#2]
### Upcoming Classes: Stock Market Course

**Title:** `Stock Market Course`
**Content:** 

> Elevate the future's stock market class is dedicated to teaching you the ins and outs of investing. We will learn all about the Stock Market, the history of it, and how you can properly invest. We will learn about Bonds, how they work, and why they are so beneficial to any investor. We will learn how to analyze markets and trends so that you can choose the right companies and the right time to invest. And finally, we will learn about portfolio management so that you can minimize risk and maximize profit! Take control of your financial future and sign up today!!!

**Link:** `https://tinyurl.com/etfstocks`

**Comment by MikeRomaa** [comment]
I need a date

**Comment by haoteng10** [comment]
> I need a date

Rolling basis & continuous

Tentatively start date of the first session: November 8, 2020

**Comment by MikeRomaa** [comment]
Resolved by commits ad50c913daab82c41ec1a497836b1e3f8c5e0a7c and 8d6127e69bd91f2d886a4f00a62c9ffbbfb42a6c.
